name = "FuzzCraft 4"
author = "FuzzyMelon94"
version = "0.7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8fd12d884c5f9df96a7dbf014c97d7649c5c279cca939075d0b3dcc5b4ff50ab"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"

[options]
datapack-folder = "config/paxi/datapacks"
