name = "FuzzCraft 4"
author = "FuzzyMelon94"
version = "0.6.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0cdacd926c0dfc563e6794518514573885ff39a19e89ab457c548ea3875901f3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"

[options]
datapack-folder = "config/paxi/datapacks"
